# Generated by Django 4.2.4 on 2023-08-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryname',
            new_name='category_name',
        ),
    ]
