# Generated by Django 4.2.4 on 2023-08-29 23:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_wacthlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='wacthlist',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, null=True, related_name='listingWatchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
